# Generated by Django 4.2.20 on 2025-07-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_additions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('MOBILE', 'Mobile Money')], max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HRM.employee')),
            ],
            options={
                'ordering': ['period', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAdditionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calendar_type', models.CharField(choices=[('GREGORIAN', 'Gregorian'), ('ETHIOPIAN', 'Ethiopian')], default='GREGORIAN', max_length=10)),
                ('start_day', models.PositiveIntegerField(help_text='Day of month when payroll period starts')),
                ('payment_day', models.PositiveIntegerField(help_text='Day of month when payment is made')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDeductionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_tax_exempt', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtimes', to='HRM.employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_type',
            field=models.CharField(blank=True, choices=[('WEEKDAY', 'Weekday'), ('WEEKEND', 'Weekend'), ('HOLIDAY', 'Holiday'), ('NIGHT', 'Night Shift')], max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='regular_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HRM.payrollcalendar')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRM.employee')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('calendar', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HRM.payrolldeductiontype')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='HRM.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('addition_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HRM.payrolladditiontype')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additions', to='HRM.payroll')),
            ],
        ),
        migrations.AddField(
            model_name='payroll',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HRM.payrollperiod'),
        ),
        migrations.CreateModel(
            name='OvertimePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('overtime_type', models.CharField(choices=[('WEEKDAY', 'Weekday'), ('WEEKEND', 'Weekend'), ('HOLIDAY', 'Holiday'), ('NIGHT', 'Night Shift')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Multiplier of base salary', max_digits=5)),
                ('minimum_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Overtime Policies',
                'unique_together': {('overtime_type', 'effective_date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'period')},
        ),
    ]
