# Generated by Django 4.2.20 on 2025-07-25 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0003_user_is_company_admin_alter_position_job_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='review',
        ),
        migrations.AddField(
            model_name='performancereview',
            name='max_rating_point',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='max_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='overall_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM.employee')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM.goal')),
            ],
        ),
    ]
