# Generated by Django 4.2.20 on 2025-07-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0004_remove_goal_employee_remove_goal_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeegoal',
            name='max_rating_point',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='employeegoal',
            name='overall_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
