# Generated by Django 4.2.20 on 2025-08-04 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0006_branch_event_pension_company_company_type_transfer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='overtime_rate',
        ),
        migrations.AddField(
            model_name='overtimepolicy',
            name='hourly_rate',
            field=models.FloatField(default=0, help_text='Hourly rate for overtime calculation'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='overtimepolicy',
            name='overtime_type',
            field=models.CharField(choices=[('WEEKDAY', 'Weekday'), ('WEEKEND', 'Weekend'), ('HOLIDAY', 'Holiday'), ('NIGHT', 'Night Shift')], max_length=10, unique=True),
        ),
    ]
