# Generated by Django 4.2.20 on 2025-08-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0007_remove_attendance_overtime_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'company')},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
