# Generated by Django 4.2.20 on 2025-08-05 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0008_alter_user_options_alter_user_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('services_included', models.CharField(blank=True, choices=[('HR Management', 'HR Management'), ('Payroll Management', 'Payroll Management'), ('Attendance Tracking', 'Attendance Tracking'), ('Leave Management', 'Leave Management'), ('Performance Reviews', 'Performance Reviews'), ('Recruitment', 'Recruitment'), ('Training Management', 'Training Management'), ('Document Management', 'Document Management'), ('Employee Self-Service Portal', 'Employee Self-Service Portal')], max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_users', models.PositiveIntegerField(default=0)),
                ('duration_months', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM.company')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HRM.subscriptionplan')),
            ],
        ),
    ]
