# Generated by Django 4.2.20 on 2025-08-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0009_subscriptionplan_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='company',
        ),
    ]
