# Generated by Django 4.2.20 on 2025-08-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0011_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subdomain',
            field=models.CharField(max_length=50),
        ),
    ]
