# Generated by Django 4.2.20 on 2025-08-05 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0012_alter_company_subdomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='services_included',
        ),
        migrations.CreateModel(
            name='SubscriptionPlanService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('HR Management', 'HR Management'), ('Payroll Management', 'Payroll Management'), ('Attendance Tracking', 'Attendance Tracking'), ('Leave Management', 'Leave Management'), ('Performance Reviews', 'Performance Reviews'), ('Recruitment', 'Recruitment'), ('Training Management', 'Training Management'), ('Document Management', 'Document Management'), ('Employee Self-Service Portal', 'Employee Self-Service Portal')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='HRM.subscriptionplan')),
            ],
        ),
    ]
