# Generated by Django 4.2.20 on 2025-08-05 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0013_remove_subscriptionplan_services_included_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplanservice',
            name='description',
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subscription_payments/')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('PayPal', 'PayPal')], max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='HRM.subscription')),
            ],
        ),
    ]
