# Generated by Django 4.2.20 on 2025-08-05 13:52

import HRM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0014_remove_subscriptionplanservice_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=HRM.models.get_subscription_payment_image_upload_path, validators=[HRM.models.validate_subscription_payment_picture]),
        ),
    ]
