# Generated by Django 4.2.20 on 2025-08-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0015_alter_subscriptionpayment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price',
        ),
        migrations.AddField(
            model_name='subscriptionplanservice',
            name='price',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
